name: Python Workflow

on: 
  workflow_dispatch:

jobs:
  unfollow:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run main.py
      env:
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        UNFOLLOW_WHITE_LIST: ${{ vars.UNFOLLOW_WHITE_LIST }}
      run: python main.py
